# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrationSystem.ui'
#
# Created: Tue Jul 22 10:55:23 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalibrationUI(object):
    def setupUi(self, CalibrationUI):
        CalibrationUI.setObjectName("CalibrationUI")
        CalibrationUI.resize(1772, 1153)
        CalibrationUI.setMinimumSize(QtCore.QSize(1400, 1100))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        CalibrationUI.setFont(font)
        self.centralwidget = QtWidgets.QWidget(CalibrationUI)
        self.centralwidget.setObjectName("centralwidget")
        self.videoFrame = QtWidgets.QLabel(self.centralwidget)
        self.videoFrame.setGeometry(QtCore.QRect(20, 70, 1280, 960))
        self.videoFrame.setObjectName("videoFrame")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 411, 61))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1310, 70, 441, 917))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonDown = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonDown.setFont(font)
        self.buttonDown.setObjectName("buttonDown")
        self.gridLayout.addWidget(self.buttonDown, 13, 1, 1, 1)
        self.buttonUp = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonUp.setFont(font)
        self.buttonUp.setObjectName("buttonUp")
        self.gridLayout.addWidget(self.buttonUp, 11, 1, 1, 1)
        self.buttonCenter = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCenter.setFont(font)
        self.buttonCenter.setObjectName("buttonCenter")
        self.gridLayout.addWidget(self.buttonCenter, 15, 0, 1, 3)
        self.buttonRight = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonRight.setFont(font)
        self.buttonRight.setObjectName("buttonRight")
        self.gridLayout.addWidget(self.buttonRight, 12, 2, 1, 1)
        self.sourceDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sourceDesc.setFont(font)
        self.sourceDesc.setObjectName("sourceDesc")
        self.gridLayout.addWidget(self.sourceDesc, 0, 0, 1, 1)
        self.sourceCombo = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sourceCombo.setFont(font)
        self.sourceCombo.setObjectName("sourceCombo")
        self.gridLayout.addWidget(self.sourceCombo, 0, 1, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 8, 0, 1, 3)
        self.widthLine = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widthLine.setFont(font)
        self.widthLine.setObjectName("widthLine")
        self.gridLayout.addWidget(self.widthLine, 4, 0, 1, 3)
        self.buttonSet = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonSet.setFont(font)
        self.buttonSet.setToolTip("")
        self.buttonSet.setObjectName("buttonSet")
        self.gridLayout.addWidget(self.buttonSet, 7, 0, 1, 3)
        self.framewDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.framewDesc.setFont(font)
        self.framewDesc.setObjectName("framewDesc")
        self.gridLayout.addWidget(self.framewDesc, 3, 0, 1, 3)
        self.scaling = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scaling.setFont(font)
        self.scaling.setObjectName("scaling")
        self.gridLayout.addWidget(self.scaling, 9, 0, 1, 3)
        self.buttonSave = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonSave.setFont(font)
        self.buttonSave.setObjectName("buttonSave")
        self.gridLayout.addWidget(self.buttonSave, 17, 0, 1, 3)
        self.buttonReset = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonReset.setFont(font)
        self.buttonReset.setObjectName("buttonReset")
        self.gridLayout.addWidget(self.buttonReset, 16, 0, 1, 3)
        self.buttonLeft = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonLeft.setFont(font)
        self.buttonLeft.setObjectName("buttonLeft")
        self.gridLayout.addWidget(self.buttonLeft, 12, 0, 1, 1)
        self.scalingSlider = QtWidgets.QSlider(self.layoutWidget)
        self.scalingSlider.setMinimum(1)
        self.scalingSlider.setMaximum(30)
        self.scalingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scalingSlider.setObjectName("scalingSlider")
        self.gridLayout.addWidget(self.scalingSlider, 10, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 14, 0, 1, 3)
        self.resDesc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.resDesc.setFont(font)
        self.resDesc.setObjectName("resDesc")
        self.gridLayout.addWidget(self.resDesc, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 2)
        CalibrationUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CalibrationUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1772, 47))
        self.menubar.setObjectName("menubar")
        CalibrationUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CalibrationUI)
        self.statusbar.setObjectName("statusbar")
        CalibrationUI.setStatusBar(self.statusbar)

        self.retranslateUi(CalibrationUI)
        QtCore.QMetaObject.connectSlotsByName(CalibrationUI)
        CalibrationUI.setTabOrder(self.sourceCombo, self.comboBox)
        CalibrationUI.setTabOrder(self.comboBox, self.widthLine)
        CalibrationUI.setTabOrder(self.widthLine, self.buttonSet)
        CalibrationUI.setTabOrder(self.buttonSet, self.buttonCenter)
        CalibrationUI.setTabOrder(self.buttonCenter, self.buttonSave)
        CalibrationUI.setTabOrder(self.buttonSave, self.buttonReset)
        CalibrationUI.setTabOrder(self.buttonReset, self.buttonUp)
        CalibrationUI.setTabOrder(self.buttonUp, self.buttonDown)
        CalibrationUI.setTabOrder(self.buttonDown, self.scalingSlider)
        CalibrationUI.setTabOrder(self.scalingSlider, self.buttonRight)
        CalibrationUI.setTabOrder(self.buttonRight, self.buttonLeft)

    def retranslateUi(self, CalibrationUI):
        _translate = QtCore.QCoreApplication.translate
        CalibrationUI.setWindowTitle(_translate("CalibrationUI", "NemPy Tracker Calibration"))
        self.videoFrame.setText(_translate("CalibrationUI", "Select source to see video displayed here"))
        self.label.setText(_translate("CalibrationUI", "Video Display"))
        self.buttonDown.setText(_translate("CalibrationUI", "Down"))
        self.buttonUp.setText(_translate("CalibrationUI", "Up"))
        self.buttonCenter.setText(_translate("CalibrationUI", "Center"))
        self.buttonRight.setText(_translate("CalibrationUI", "Right"))
        self.sourceDesc.setText(_translate("CalibrationUI", "Source"))
        self.buttonSet.setText(_translate("CalibrationUI", "Set"))
        self.framewDesc.setText(_translate("CalibrationUI", "Frame width (in mm)"))
        self.scaling.setText(_translate("CalibrationUI", "TextLabel"))
        self.buttonSave.setText(_translate("CalibrationUI", "Save"))
        self.buttonReset.setText(_translate("CalibrationUI", "Reset"))
        self.buttonLeft.setText(_translate("CalibrationUI", "Left"))
        self.resDesc.setText(_translate("CalibrationUI", "Resolution"))
        self.comboBox.setItemText(0, _translate("CalibrationUI", "1280 x 960"))
        self.comboBox.setItemText(1, _translate("CalibrationUI", "1280 x 720"))
        self.comboBox.setItemText(2, _translate("CalibrationUI", "640 x 480"))

