# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrationSystem.ui'
#
# Created: Thu Jul 31 21:16:30 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalibrationUI(object):
    def setupUi(self, CalibrationUI):
        CalibrationUI.setObjectName("CalibrationUI")
        CalibrationUI.resize(1000, 650)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        CalibrationUI.setFont(font)
        self.centralwidget = QtWidgets.QWidget(CalibrationUI)
        self.centralwidget.setObjectName("centralwidget")
        self.controls = QtWidgets.QWidget(self.centralwidget)
        self.controls.setGeometry(QtCore.QRect(820, 10, 170, 497))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.controls.setFont(font)
        self.controls.setObjectName("controls")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controls)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sourceDesc = QtWidgets.QLabel(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sourceDesc.setFont(font)
        self.sourceDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.sourceDesc.setObjectName("sourceDesc")
        self.verticalLayout.addWidget(self.sourceDesc)
        self.sourceCombo = QtWidgets.QComboBox(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sourceCombo.setFont(font)
        self.sourceCombo.setObjectName("sourceCombo")
        self.verticalLayout.addWidget(self.sourceCombo)
        self.line_2 = QtWidgets.QFrame(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.resDesc = QtWidgets.QLabel(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resDesc.setFont(font)
        self.resDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.resDesc.setObjectName("resDesc")
        self.verticalLayout.addWidget(self.resDesc)
        self.comboBox = QtWidgets.QComboBox(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.line = QtWidgets.QFrame(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.framewDesc = QtWidgets.QLabel(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.framewDesc.setFont(font)
        self.framewDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.framewDesc.setObjectName("framewDesc")
        self.verticalLayout.addWidget(self.framewDesc)
        self.widthLine = QtWidgets.QLineEdit(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widthLine.setFont(font)
        self.widthLine.setObjectName("widthLine")
        self.verticalLayout.addWidget(self.widthLine)
        self.buttonSet = QtWidgets.QPushButton(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonSet.setFont(font)
        self.buttonSet.setToolTip("")
        self.buttonSet.setObjectName("buttonSet")
        self.verticalLayout.addWidget(self.buttonSet)
        self.line_3 = QtWidgets.QFrame(self.controls)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.scaling = QtWidgets.QLabel(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scaling.setFont(font)
        self.scaling.setAlignment(QtCore.Qt.AlignCenter)
        self.scaling.setObjectName("scaling")
        self.verticalLayout.addWidget(self.scaling)
        self.scalingSlider = QtWidgets.QSlider(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scalingSlider.setFont(font)
        self.scalingSlider.setMinimum(1)
        self.scalingSlider.setMaximum(30)
        self.scalingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scalingSlider.setObjectName("scalingSlider")
        self.verticalLayout.addWidget(self.scalingSlider)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonUp = QtWidgets.QPushButton(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonUp.setFont(font)
        self.buttonUp.setObjectName("buttonUp")
        self.gridLayout_2.addWidget(self.buttonUp, 0, 1, 1, 1)
        self.buttonLeft = QtWidgets.QPushButton(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonLeft.setFont(font)
        self.buttonLeft.setObjectName("buttonLeft")
        self.gridLayout_2.addWidget(self.buttonLeft, 1, 0, 1, 1)
        self.buttonRight = QtWidgets.QPushButton(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonRight.setFont(font)
        self.buttonRight.setObjectName("buttonRight")
        self.gridLayout_2.addWidget(self.buttonRight, 1, 2, 1, 1)
        self.buttonDown = QtWidgets.QPushButton(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonDown.setFont(font)
        self.buttonDown.setObjectName("buttonDown")
        self.gridLayout_2.addWidget(self.buttonDown, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_5 = QtWidgets.QFrame(self.controls)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.buttonCenter = QtWidgets.QPushButton(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCenter.setFont(font)
        self.buttonCenter.setObjectName("buttonCenter")
        self.verticalLayout.addWidget(self.buttonCenter)
        self.buttonReset = QtWidgets.QPushButton(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonReset.setFont(font)
        self.buttonReset.setObjectName("buttonReset")
        self.verticalLayout.addWidget(self.buttonReset)
        self.buttonSave = QtWidgets.QPushButton(self.controls)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonSave.setFont(font)
        self.buttonSave.setObjectName("buttonSave")
        self.verticalLayout.addWidget(self.buttonSave)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 800, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.videoFrame = QtWidgets.QLabel(self.widget)
        self.videoFrame.setMaximumSize(QtCore.QSize(1000, 650))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.videoFrame.setFont(font)
        self.videoFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.videoFrame.setObjectName("videoFrame")
        self.horizontalLayout.addWidget(self.videoFrame)
        CalibrationUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CalibrationUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 28))
        self.menubar.setObjectName("menubar")
        CalibrationUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CalibrationUI)
        self.statusbar.setObjectName("statusbar")
        CalibrationUI.setStatusBar(self.statusbar)

        self.retranslateUi(CalibrationUI)
        QtCore.QMetaObject.connectSlotsByName(CalibrationUI)
        CalibrationUI.setTabOrder(self.sourceCombo, self.comboBox)
        CalibrationUI.setTabOrder(self.comboBox, self.buttonCenter)
        CalibrationUI.setTabOrder(self.buttonCenter, self.buttonSave)
        CalibrationUI.setTabOrder(self.buttonSave, self.buttonReset)

    def retranslateUi(self, CalibrationUI):
        _translate = QtCore.QCoreApplication.translate
        CalibrationUI.setWindowTitle(_translate("CalibrationUI", "NemPy Tracker Calibration"))
        self.sourceDesc.setText(_translate("CalibrationUI", "Source"))
        self.resDesc.setText(_translate("CalibrationUI", "Resolution"))
        self.comboBox.setItemText(0, _translate("CalibrationUI", "1280 x 960"))
        self.comboBox.setItemText(1, _translate("CalibrationUI", "1280 x 720"))
        self.comboBox.setItemText(2, _translate("CalibrationUI", "640 x 480"))
        self.framewDesc.setText(_translate("CalibrationUI", "Frame width (in mm)"))
        self.buttonSet.setText(_translate("CalibrationUI", "Set"))
        self.scaling.setText(_translate("CalibrationUI", "TextLabel"))
        self.buttonUp.setText(_translate("CalibrationUI", "Up"))
        self.buttonLeft.setText(_translate("CalibrationUI", "Left"))
        self.buttonRight.setText(_translate("CalibrationUI", "Right"))
        self.buttonDown.setText(_translate("CalibrationUI", "Down"))
        self.buttonCenter.setText(_translate("CalibrationUI", "Center"))
        self.buttonReset.setText(_translate("CalibrationUI", "Reset"))
        self.buttonSave.setText(_translate("CalibrationUI", "Save"))
        self.videoFrame.setText(_translate("CalibrationUI", "Select source to see video displayed here"))

